"""
atlas_v0_map_d_capital_stack.py
================================
Displacement Defense Atlas v0 — Map (d), Five-Layer Capital Stack Composite
Dallas County, TX | Thesis: "Below the Line" | Nicholas Donovan Hawkins, TSU

ANALYTICAL PURPOSE
------------------
Map D is the V5 thesis's signature spatial argument: a six-panel 300 DPI
publication figure that renders each of the five capital-stack layers as a
stand-alone choropleth (A–E) and then composites them into a single
`capital_stack_score` choropleth (F). The composite operationalizes the
claim from `docs/theory/five_layer_capital_stack.md` that Dallas's public-
finance architecture is vertically integrated — that the layers compound.
Panels (A)–(E) allow visual verification that the composite is not driven
by any one layer alone. Panel (F) is the headline map for Chapter 4.

PANEL LAYOUT (2 rows × 3 columns)
---------------------------------
    (A) Layer 1 — CIP per capita (2012–present bond projects spatial-joined)
    (B) Layer 2 — PID annual budget per capita
    (C) Layer 3 — TIF / Opportunity Zone presence (binary any)
    (D) Layer 4 — Institutional-pressure proxy (real 10-yr gentrification
        or demographic-change signal; DCAD SFR pipeline pending)
    (E) Layer 5 — Vendor economic residue (5 mi vendor-capture share)
    (F) Composite — capital_stack_score (mean of A–E, each normalized 0–1)

INPUTS
------
    outputs/tables/capital_stack_inputs_v1.csv   (generated by this script
                                                 if missing; 645 tracts)
    outputs/geojson/tracts_pid_join.geojson      (Dallas County tract geometry)

OUTPUTS
-------
    maps/v0/atlas_map_d_capital_stack.png             (300 DPI)
    outputs/figures/atlas_v0_map_d_capital_stack.png  (300 DPI copy)

USAGE
-----
    python scripts/analysis/h3_pid_bates_hmda/atlas_v0_map_d_capital_stack.py

LAYER 4 CAVEAT
--------------
The Layer 4 choropleth uses a demographic-change proxy (real_gent_signal OR
demo_change_real from `h6_bates_full_typology.csv`). The canonical Layer 4
variable `sfr_investor_share` will be supplied when the DCAD institutional
ownership pipeline (`scripts/analysis/h4_sfr_institutional/
h4_sfr_institutional_flag.py`) has completed. This script reads from the
composite input file so the swap is one-line when DCAD output lands.
"""

from __future__ import annotations

import os
import warnings
from pathlib import Path

import numpy as np
import pandas as pd
import geopandas as gpd
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import matplotlib.lines as mlines
import matplotlib.colors as mcolors
from matplotlib.cm import ScalarMappable
from shapely.geometry import LineString, Point

warnings.filterwarnings("ignore", category=FutureWarning)
warnings.filterwarnings("ignore", category=UserWarning)

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------

REPO_ROOT   = Path(__file__).resolve().parents[3]
H6_PATH     = REPO_ROOT / "outputs" / "tables" / "h6_bates_full_typology.csv"
PID_PATH    = REPO_ROOT / "outputs" / "tables" / "pid_tract_join.csv"
CIP_PATH    = REPO_ROOT / "data" / "raw" / "layer1_investment" / "CIP_Points_All_Bonds.csv"
INPUT_PATH  = REPO_ROOT / "outputs" / "tables" / "capital_stack_inputs_v1.csv"
TRACT_GEO   = REPO_ROOT / "outputs" / "geojson" / "tracts_pid_join.geojson"

OUT_PRIMARY   = REPO_ROOT / "maps" / "v0" / "atlas_map_d_capital_stack.png"
OUT_SECONDARY = REPO_ROOT / "outputs" / "figures" / "atlas_v0_map_d_capital_stack.png"

# ---------------------------------------------------------------------------
# Figure configuration
# ---------------------------------------------------------------------------

FIG_WIDTH  = 20
FIG_HEIGHT = 14
DPI        = 300

SUPTITLE = "The Five-Layer Capital Stack — Dallas County Census Tracts (2013–2023)"
SUBTITLE = "Compounded investment, tool presence, and vendor residue vs. the I-30 dividing line"
FOOTNOTE = (
    "Sources: City of Dallas CIP FY2012–present (bond points spatial-joined to tracts); "
    "Dallas OED PID boundaries & 2024 annual budgets; 2025 Dallas TIF Annual Report; CDFI Fund OZ designations; "
    "Dallas Vendor Payments FY2019–present (145,551 rows; top-18 vendor residue 5-mi buffer); "
    "ACS 5-yr 2013 & 2023 (CPI-adjusted); LTDB/UDP Bates Typology v2.1.  Layer 4 uses "
    "a real-gentrification/demographic-change proxy pending DCAD institutional-SFR pipeline output.  |  "
    "Hawkins (2027), Below the Line, TSU"
)

# --- I-30 reference line ---------------------------------------------------
I30_COORDS_WGS84 = [(-97.10, 32.75), (-96.55, 32.75)]

# ---------------------------------------------------------------------------
# Layer specs — title, column in input CSV, colormap, legend units, note
# ---------------------------------------------------------------------------
LAYER_SPECS = [
    {
        "key":     "L1_cip_norm",
        "letter":  "A",
        "title":   "Layer 1 — CIP Per Capita",
        "subtitle":"Public base · FY2012–present bond projects",
        "raw_col": "cip_per_cap",
        "raw_fmt": lambda v: f"${v:,.0f}/capita",
        "cmap":    "Greens",
    },
    {
        "key":     "L2_pid_norm",
        "letter":  "B",
        "title":   "Layer 2 — PID Per Capita",
        "subtitle":"Private supplementation · 33× gap documented",
        "raw_col": "pid_per_cap",
        "raw_fmt": lambda v: f"${v:,.0f}/capita",
        "cmap":    "Purples",
    },
    {
        "key":     "L3_tool_norm",
        "letter":  "C",
        "title":   "Layer 3 — TIF / Opportunity Zone",
        "subtitle":"Financial engineering · binary presence",
        "raw_col": "l3_tool_any",
        "raw_fmt": lambda v: "TIF/OZ present" if v>0 else "Neither",
        "cmap":    "Blues",
        "binary":  True,
    },
    {
        "key":     "L4_pressure_norm",
        "letter":  "D",
        "title":   "Layer 4 — Institutional Pressure  (proxy)",
        "subtitle":"Real-gentrification or demographic-change signal",
        "raw_col": "l4_pressure_proxy",
        "raw_fmt": lambda v: "Signal present" if v>0 else "No signal",
        "cmap":    "Oranges",
        "binary":  True,
    },
    {
        "key":     "L5_vendor_norm",
        "letter":  "E",
        "title":   "Layer 5 — Vendor Residue (5-mi share)",
        "subtitle":"Where public contracting dollars land · 12.6× gap",
        "raw_col": "l5_vendor_share",
        "raw_fmt": lambda v: f"{v*100:.2f}% share",
        "cmap":    "Reds",
    },
    {
        "key":     "capital_stack_score",
        "letter":  "F",
        "title":   "Capital Stack Composite (mean of A–E)",
        "subtitle":"High = stacked advantage · Low = stacked disinvestment",
        "raw_col": "capital_stack_score",
        "raw_fmt": lambda v: f"{v:.2f}",
        "cmap":    "RdYlGn",  # green = stacked advantage (high), red = stacked disinvestment (low)
        "composite": True,
    },
]


# ---------------------------------------------------------------------------
# Map furniture
# ---------------------------------------------------------------------------

def add_north_arrow(ax, x: float = 0.94, y: float = 0.94, fontsize: int = 9) -> None:
    ax.annotate(
        "N\n▲",
        xy=(x, y), xycoords="axes fraction",
        ha="center", va="center",
        fontsize=fontsize, fontweight="bold", fontfamily="DejaVu Sans",
        bbox=dict(boxstyle="round,pad=0.2", facecolor="white",
                  edgecolor="#444444", linewidth=0.6, alpha=0.92),
    )


def add_scalebar(ax, length_m: float = 8047, label: str = "5 mi",
                 x0_frac: float = 0.05, y0_frac: float = 0.06) -> None:
    xlim = ax.get_xlim()
    ylim = ax.get_ylim()
    map_width_m  = xlim[1] - xlim[0]
    map_height_m = ylim[1] - ylim[0]
    x0 = xlim[0] + x0_frac * map_width_m
    y0 = ylim[0] + y0_frac * map_height_m
    ax.plot([x0, x0 + length_m], [y0, y0],
            color="black", linewidth=1.6, solid_capstyle="butt", zorder=7)
    for xt in (x0, x0 + length_m):
        ax.plot([xt, xt],
                [y0 - map_height_m * 0.005, y0 + map_height_m * 0.005],
                color="black", linewidth=1.2, zorder=7)
    ax.text(x0 + length_m / 2, y0 + map_height_m * 0.014,
            label, ha="center", va="bottom",
            fontsize=7, fontfamily="DejaVu Sans", zorder=7)


# ---------------------------------------------------------------------------
# Input builder — produces the capital_stack_inputs_v1.csv if missing
# ---------------------------------------------------------------------------

def build_inputs() -> pd.DataFrame:
    """Construct tract-level capital stack input table from raw sources."""
    if INPUT_PATH.exists():
        print(f"[Map D] Loading cached inputs → {INPUT_PATH.name}")
        return pd.read_csv(INPUT_PATH, dtype={"GEOID": str})

    print("[Map D] Building inputs from raw sources...")
    tracts = gpd.read_file(TRACT_GEO)
    tracts["GEOID"] = tracts["GEOID"].astype(str).str.zfill(11)
    tracts_wm = tracts.to_crs(epsg=3857)

    # Layer 1 — CIP spatial-join
    cip = pd.read_csv(CIP_PATH).dropna(subset=["latitude", "longitude", "BondAmount"])
    cip_gdf = gpd.GeoDataFrame(
        cip, geometry=gpd.points_from_xy(cip["longitude"], cip["latitude"]),
        crs="EPSG:4326",
    ).to_crs(epsg=3857)
    joined = gpd.sjoin(
        cip_gdf, tracts_wm[["GEOID", "geometry"]],
        predicate="within", how="left",
    )
    l1 = joined.groupby("GEOID", dropna=True)["BondAmount"].sum() \
               .reset_index(name="cip_total_usd")

    # Base columns from H6
    h6 = pd.read_csv(H6_PATH, dtype={"GEOID": str})
    h6["GEOID"] = h6["GEOID"].str.zfill(11)
    df = h6[[
        "GEOID", "pop_2023", "south_of_i30", "bates_typology_v21",
        "tif_present", "oz_designated", "in_pid", "vendor_share_5mi",
        "real_gent_signal", "demo_change_real", "vuln_index",
    ]].merge(l1, on="GEOID", how="left")
    df["cip_total_usd"] = df["cip_total_usd"].fillna(0)
    df["cip_per_cap"] = df.apply(
        lambda r: r["cip_total_usd"] / r["pop_2023"] if r["pop_2023"] > 0 else 0,
        axis=1,
    )

    # Layer 2 — PID budget per capita
    pid = pd.read_csv(PID_PATH, dtype={"GEOID": str})
    pid["GEOID"] = pid["GEOID"].str.zfill(11)
    df = df.merge(pid[["GEOID", "pid_annual_budget"]], on="GEOID", how="left")
    df["pid_annual_budget"] = df["pid_annual_budget"].fillna(0)
    df["pid_per_cap"] = df.apply(
        lambda r: r["pid_annual_budget"] / r["pop_2023"] if r["pop_2023"] > 0 else 0,
        axis=1,
    )

    # Layer 3 — binary any tool
    df["l3_tool_any"] = ((df["tif_present"] == 1) | (df["oz_designated"] == 1)).astype(int)

    # Layer 4 — pressure proxy
    df["l4_pressure_proxy"] = (
        (df["real_gent_signal"] == 1) | (df["demo_change_real"] == 1)
    ).astype(int)

    # Layer 5 — vendor residue
    df["l5_vendor_share"] = df["vendor_share_5mi"].fillna(0)

    # Normalize 0-1 (99th-pctile winsorized for continuous layers)
    def mm(s: pd.Series) -> pd.Series:
        lo, hi = s.min(), s.max()
        return (s - lo) / (hi - lo) if hi > lo else s * 0

    df["L1_cip_norm"]      = mm(df["cip_per_cap"].clip(upper=df["cip_per_cap"].quantile(0.99)))
    df["L2_pid_norm"]      = mm(df["pid_per_cap"].clip(upper=df["pid_per_cap"].quantile(0.99)))
    df["L3_tool_norm"]     = df["l3_tool_any"].astype(float)
    df["L4_pressure_norm"] = df["l4_pressure_proxy"].astype(float)
    df["L5_vendor_norm"]   = mm(
        df["l5_vendor_share"].clip(upper=df["l5_vendor_share"].quantile(0.99))
    )

    df["capital_stack_score"] = df[[
        "L1_cip_norm", "L2_pid_norm", "L3_tool_norm",
        "L4_pressure_norm", "L5_vendor_norm",
    ]].mean(axis=1)

    INPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    df.to_csv(INPUT_PATH, index=False)
    print(f"[Map D] Saved inputs → {INPUT_PATH.relative_to(REPO_ROOT)}")
    return df


# ---------------------------------------------------------------------------
# Panel renderer
# ---------------------------------------------------------------------------

def render_panel(ax, gdf_wm: gpd.GeoDataFrame, spec: dict,
                 i30_wm: gpd.GeoDataFrame,
                 county_boundary: gpd.GeoDataFrame) -> None:
    """Render a single capital-stack layer panel."""
    col = spec["key"]
    cmap = plt.get_cmap(spec["cmap"])

    if spec.get("binary"):
        # Two-class fill
        for val, color in [(0, "#f0f0f0"), (1, cmap(0.75))]:
            mask = gdf_wm[col] == val
            if mask.sum() > 0:
                gdf_wm[mask].plot(
                    ax=ax, facecolor=color, edgecolor="#aaaaaa",
                    linewidth=0.2, zorder=2,
                )
    else:
        gdf_wm.plot(
            ax=ax, column=col, cmap=cmap, vmin=0, vmax=1,
            edgecolor="#cccccc", linewidth=0.2, zorder=2,
        )

    # County outline + I-30
    county_boundary.plot(
        ax=ax, facecolor="none", edgecolor="#222222",
        linewidth=1.0, zorder=5,
    )
    i30_wm.plot(
        ax=ax, color="black", linestyle="--", linewidth=1.4, zorder=6,
    )

    # Extent
    bounds = gdf_wm.total_bounds
    pad_x = (bounds[2] - bounds[0]) * 0.04
    pad_y = (bounds[3] - bounds[1]) * 0.04
    ax.set_xlim(bounds[0] - pad_x, bounds[2] + pad_x)
    ax.set_ylim(bounds[1] - pad_y, bounds[3] + pad_y)
    ax.set_aspect("equal")
    ax.set_axis_off()

    add_north_arrow(ax)
    add_scalebar(ax)

    # Emphasize composite panel with thicker border
    if spec.get("composite"):
        for side in ("top", "right", "bottom", "left"):
            ax.spines[side].set_visible(False)
        # Panel outer highlight rectangle
        rect = mpatches.Rectangle(
            (0.002, 0.002), 0.996, 0.996, transform=ax.transAxes,
            fill=False, edgecolor="#7f0000", linewidth=2.2, zorder=10,
        )
        ax.add_patch(rect)

    # Panel title (letter + title + subtitle)
    panel_title = f"{spec['letter']}.  {spec['title']}"
    ax.set_title(
        f"{panel_title}\n{spec['subtitle']}",
        fontsize=11, fontweight="bold", fontfamily="DejaVu Sans",
        loc="left", pad=6,
    )

    # Colorbar / legend
    if spec.get("binary"):
        handles = [
            mpatches.Patch(facecolor="#f0f0f0", edgecolor="#aaaaaa",
                           label="Absent"),
            mpatches.Patch(facecolor=cmap(0.75), edgecolor="#aaaaaa",
                           label="Present"),
        ]
        leg = ax.legend(
            handles=handles, loc="lower right",
            fontsize=7.5, frameon=True, framealpha=0.92,
            edgecolor="#aaaaaa", fancybox=False,
        )
    else:
        # Compact inset colorbar
        sm = ScalarMappable(cmap=cmap, norm=mcolors.Normalize(vmin=0, vmax=1))
        sm.set_array([])
        cax = ax.inset_axes([0.72, 0.08, 0.22, 0.025])
        cb = plt.colorbar(sm, cax=cax, orientation="horizontal")
        cb.ax.tick_params(labelsize=6, length=2)
        cb.set_label("normalized (0–1)", fontsize=6.5,
                     fontfamily="DejaVu Sans", labelpad=2)


# ---------------------------------------------------------------------------
# Main builder
# ---------------------------------------------------------------------------

def build_figure() -> None:
    df = build_inputs()
    print(f"[Map D] Inputs: {len(df)} tracts")

    # Join geometry
    tracts = gpd.read_file(TRACT_GEO)
    tracts["GEOID"] = tracts["GEOID"].astype(str).str.zfill(11)
    df["GEOID"] = df["GEOID"].astype(str).str.zfill(11)
    gdf = tracts.merge(df, on="GEOID", how="left").to_crs(epsg=3857)

    # Shared geometry
    i30_wm = gpd.GeoDataFrame(
        geometry=[LineString(I30_COORDS_WGS84)], crs="EPSG:4326"
    ).to_crs(epsg=3857)
    county_boundary = gdf.dissolve()

    # 2×3 grid
    fig, axes = plt.subplots(
        2, 3, figsize=(FIG_WIDTH, FIG_HEIGHT), dpi=DPI,
        gridspec_kw=dict(wspace=0.02, hspace=0.18),
    )

    for ax, spec in zip(axes.flatten(), LAYER_SPECS):
        render_panel(ax, gdf, spec, i30_wm, county_boundary)

    # Suptitle + subtitle
    fig.suptitle(SUPTITLE, fontsize=17, fontweight="bold",
                 fontfamily="DejaVu Sans", y=0.985)
    fig.text(
        0.5, 0.955, SUBTITLE,
        fontsize=11, fontstyle="italic", fontfamily="DejaVu Sans",
        color="#444444", ha="center",
    )

    # Footnote
    fig.text(
        0.01, 0.008, FOOTNOTE,
        fontsize=7.4, fontfamily="DejaVu Sans",
        color="#555555", ha="left", va="bottom", wrap=True,
    )

    # Save
    OUT_PRIMARY.parent.mkdir(parents=True, exist_ok=True)
    OUT_SECONDARY.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(OUT_PRIMARY, dpi=DPI, bbox_inches="tight",
                facecolor="white", edgecolor="none")
    fig.savefig(OUT_SECONDARY, dpi=DPI, bbox_inches="tight",
                facecolor="white", edgecolor="none")
    plt.close(fig)

    # Diagnostics
    print(f"[Map D] Saved → {OUT_PRIMARY.relative_to(REPO_ROOT)}")
    print(f"[Map D] Saved → {OUT_SECONDARY.relative_to(REPO_ROOT)}")
    print("\n[Map D] capital_stack_score — North vs South of I-30:")
    grp = df.groupby("south_of_i30")["capital_stack_score"].agg(["mean","std","count"])
    print(grp)
    print("\n[Map D] Bottom quartile (stacked disinvestment):")
    q25 = df["capital_stack_score"].quantile(0.25)
    bq = df[df["capital_stack_score"] <= q25]
    print(f"  n={len(bq)}; south_of_i30 share = "
          f"{(bq['south_of_i30']==1).mean()*100:.1f}%")


if __name__ == "__main__":
    build_figure()
